// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: proto/iot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Struktur Data yang dikirim
type SensorData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SensorId        string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Timestamp       float64                `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CompressionType string                 `protobuf:"bytes,3,opt,name=compression_type,json=compressionType,proto3" json:"compression_type,omitempty"`
	Data            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_proto_iot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{0}
}

func (x *SensorData) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *SensorData) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SensorData) GetCompressionType() string {
	if x != nil {
		return x.CompressionType
	}
	return ""
}

func (x *SensorData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Balasan dari Server
type ServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_proto_iot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_iot_proto_rawDescGZIP(), []int{1}
}

func (x *ServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_iot_proto protoreflect.FileDescriptor

const file_proto_iot_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/iot.proto\x12\x03iot\"\x86\x01\n" +
	"\n" +
	"SensorData\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x01R\ttimestamp\x12)\n" +
	"\x10compression_type\x18\x03 \x01(\tR\x0fcompressionType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"D\n" +
	"\x0eServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2D\n" +
	"\fDataTransfer\x124\n" +
	"\n" +
	"SendStream\x12\x0f.iot.SensorData\x1a\x13.iot.ServerResponse(\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_iot_proto_rawDescOnce sync.Once
	file_proto_iot_proto_rawDescData []byte
)

func file_proto_iot_proto_rawDescGZIP() []byte {
	file_proto_iot_proto_rawDescOnce.Do(func() {
		file_proto_iot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_iot_proto_rawDesc), len(file_proto_iot_proto_rawDesc)))
	})
	return file_proto_iot_proto_rawDescData
}

var file_proto_iot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_iot_proto_goTypes = []any{
	(*SensorData)(nil),     // 0: iot.SensorData
	(*ServerResponse)(nil), // 1: iot.ServerResponse
}
var file_proto_iot_proto_depIdxs = []int32{
	0, // 0: iot.DataTransfer.SendStream:input_type -> iot.SensorData
	1, // 1: iot.DataTransfer.SendStream:output_type -> iot.ServerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_iot_proto_init() }
func file_proto_iot_proto_init() {
	if File_proto_iot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_iot_proto_rawDesc), len(file_proto_iot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_iot_proto_goTypes,
		DependencyIndexes: file_proto_iot_proto_depIdxs,
		MessageInfos:      file_proto_iot_proto_msgTypes,
	}.Build()
	File_proto_iot_proto = out.File
	file_proto_iot_proto_goTypes = nil
	file_proto_iot_proto_depIdxs = nil
}
