// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.6
// source: proto/iot.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataTransfer_SendStream_FullMethodName = "/iot.DataTransfer/SendStream"
)

// DataTransferClient is the client API for DataTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Definisi Service (Fungsi yang bisa dipanggil)
type DataTransferClient interface {
	// Menggunakan "stream" agar data bisa mengalir terus menerus tanpa putus koneksi
	SendStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SensorData, ServerResponse], error)
}

type dataTransferClient struct {
	cc grpc.ClientConnInterface
}

func NewDataTransferClient(cc grpc.ClientConnInterface) DataTransferClient {
	return &dataTransferClient{cc}
}

func (c *dataTransferClient) SendStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SensorData, ServerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataTransfer_ServiceDesc.Streams[0], DataTransfer_SendStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SensorData, ServerResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataTransfer_SendStreamClient = grpc.ClientStreamingClient[SensorData, ServerResponse]

// DataTransferServer is the server API for DataTransfer service.
// All implementations must embed UnimplementedDataTransferServer
// for forward compatibility.
//
// Definisi Service (Fungsi yang bisa dipanggil)
type DataTransferServer interface {
	// Menggunakan "stream" agar data bisa mengalir terus menerus tanpa putus koneksi
	SendStream(grpc.ClientStreamingServer[SensorData, ServerResponse]) error
	mustEmbedUnimplementedDataTransferServer()
}

// UnimplementedDataTransferServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataTransferServer struct{}

func (UnimplementedDataTransferServer) SendStream(grpc.ClientStreamingServer[SensorData, ServerResponse]) error {
	return status.Error(codes.Unimplemented, "method SendStream not implemented")
}
func (UnimplementedDataTransferServer) mustEmbedUnimplementedDataTransferServer() {}
func (UnimplementedDataTransferServer) testEmbeddedByValue()                      {}

// UnsafeDataTransferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataTransferServer will
// result in compilation errors.
type UnsafeDataTransferServer interface {
	mustEmbedUnimplementedDataTransferServer()
}

func RegisterDataTransferServer(s grpc.ServiceRegistrar, srv DataTransferServer) {
	// If the following call panics, it indicates UnimplementedDataTransferServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataTransfer_ServiceDesc, srv)
}

func _DataTransfer_SendStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataTransferServer).SendStream(&grpc.GenericServerStream[SensorData, ServerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataTransfer_SendStreamServer = grpc.ClientStreamingServer[SensorData, ServerResponse]

// DataTransfer_ServiceDesc is the grpc.ServiceDesc for DataTransfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataTransfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iot.DataTransfer",
	HandlerType: (*DataTransferServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendStream",
			Handler:       _DataTransfer_SendStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/iot.proto",
}
