# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import iot_pb2 as iot__pb2


class DataTransferStub(object):
    """Definisi Service (Fungsi yang bisa dipanggil)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendStream = channel.stream_stream(
            '/iot.DataTransfer/SendStream',
            request_serializer=iot__pb2.SensorData.SerializeToString,
            response_deserializer=iot__pb2.ServerResponse.FromString,
        )


class DataTransferServicer(object):
    """Definisi Service (Fungsi yang bisa dipanggil)
    """

    def SendStream(self, request_iterator, context):
        """Menggunakan "stream" agar data bisa mengalir terus menerus tanpa putus koneksi
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SendStream': grpc.stream_stream_rpc_method_handler(
            servicer.SendStream,
            request_deserializer=iot__pb2.SensorData.FromString,
            response_serializer=iot__pb2.ServerResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'iot.DataTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class DataTransfer(object):
    """Definisi Service (Fungsi yang bisa dipanggil)
    """

    @staticmethod
    def SendStream(request_iterator,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/iot.DataTransfer/SendStream',
                                               iot__pb2.SensorData.SerializeToString,
                                               iot__pb2.ServerResponse.FromString,
                                               options, channel_credentials,
                                               insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
