# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tiot.proto\x12\x03iot\"V\n\nSensorData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x18\n\x10compression_type\x18\x03 \x01(\t\x12\x0c\n\x04data\x18\x04 \x01(\x0c\"3\n\x0eServerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08message\x18\x02 \x01(\t2B\n\x0cDataTransfer\x12\x32\n\nSendStream\x12\x0f.iot.SensorData\x1a\x13.iot.ServerResponseB\t\xf8\x01\x01Z\x05./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'\xf8\x01\x01Z\x05./proto'
    _globals['_SENSORDATA']._serialized_start = 18
    _globals['_SENSORDATA']._serialized_end = 104
    _globals['_SERVERRESPONSE']._serialized_start = 106
    _globals['_SERVERRESPONSE']._serialized_end = 157
    _globals['_DATATRANSFER']._serialized_start = 159
    _globals['_DATATRANSFER']._serialized_end = 225
# @@protoc_insertion_point(module_scope)
